### ISSUE TITLE
failing to parse a discard when not in collection

### ISSUE THREAD

**Issue by shaunxcode** [relevance/edn-ruby#17]
`EDN.read "[#_ a]"`

correctly gives me an empty vector

`EDN.read "#_ a"`

fails saying "Invalid EDN, cannot parse" 

I believe it should actually return nil as per `(clojure.edn/read-string "#_ a")` => nil 

This is also the case for empty strings/whitespace e.g. `" , "`.

**Comment by russolsen** [comment]
Thanks for taking the time to report the issue. There were some problem with the discard, which I think I have now fixed. But the edn Ruby API treats reading more data than is there, with or without discards, as an error. I don't want to change that at this point. You can get the behavior you are looking for with this:

     EDN.read "#_ a 44", nil
