### ISSUE TITLE
Ragel-based C extension

### ISSUE THREAD

**Issue by edporras** [relevance/edn-ruby#35]
Hi there,

I've started work on a gem for parsing EDN as my group needs to do this for large sets of document data. The main tool I am using it with reads ruby objects dumped in EDN format so I've implemented support for (I think) most or everything I need in that regard but a colleague does need it to read more complete EDN data with tagged elements and sets. I'll be working on this next but wanted to check if there's any interest in integrating it into `edn-ruby`, either replacing or, perhaps, adding an option at build time to choose between the existing ruby- and the c++/ragel-based parser. I based the project on the `json-ragel` (https://github.com/flori/json) gem source which looks to do something similar (Florian's source was indispensable in helping me understand how ragel works and who to tie it into a ruby extension. I need to credit him for this).

I maintain a couple of gems that we use internally but this is the first one I create publicly so I apologize if this is not the proper way to approach you about this. If you think you are interested, I will start looking to see how to integrate it into `edn-ruby` once I have more complete EDN support so I can submit a pull request. I wasn't planning on adding support for EDN writing since the performance hit is not significant on that end.

If you're interested in what I have so far, the source is available at [https://github.com/edporras/edn_turbo](https://github.com/edporras/edn_turbo). I have benchmarked a few documents and speed up can be highly significant depending on the content.

Hope to hear from you soon. Thank you.

**Comment by russolsen** [comment]
Hi Ed,

Thanks for reaching out. I do think there are some possibilities for working together, anything from making sure the two Ruby based EDN implementations actually produce the same answers to merging the two gems. I know there are a fair number of gems that come packaged as a native implementation along with a pure Ruby implementation, although I've never done that personally (yet).

I think the first step would be for us to adopt a common set of tests. If you are interested, take a look at the specs/ directory. For my part I'll have a look at your tests.

Russ

**Comment by edporras** [comment]
Hi Russ,

I've been looking at that and I'm continuing to add support to match things. I've just changed things to allow single element values in a stream as I was originally only handling input enclose within a list, vector, or hash. I'm reworking tagged elements right now as I'm not happy with what I did so far. Sets might be a little tricky since I'll need to build them on the C-side, and I might add support using a Rice type and them submit it to them to include in their gem.

This is my first public gem so I'm somewhat new to this. I just realized I needed to update the date in the gemspec :). I've moved that to the same file I update with the gem version. Let me work on things a little more and I'll get back to you once I'm closer, hopefully later this week.

**Comment by russolsen** [comment]
Ed,

I've reorganized many of the tests in hope that it will make it easier for us to share work. If you have a look in https://github.com/relevance/edn-ruby/tree/master/spec/exemplars you will see a bunch of pairs of files, one Ruby file for each EDN file. The idea is that  reading the EDN file you should give you the equivalent value as evaluating the corresponding Ruby code.

So, for example, this:

    EDN.read(File.read("float.edn"))

Should be equal to this:

    eval(File.read("float.rb"))

See the top of https://github.com/relevance/edn-ruby/blob/master/spec/edn_spec.rb

**Comment by edporras** [comment]
hey Russ, sounds great. I've been busy with some issues - including a bit of a bug that knocked me out for a day - so I apologize for the silence. Still dealing with how to handle ruby-types such as Date that are needed in the output generated by the C-side.

**Comment by edporras** [comment]
Hi Russ,

I have `inst` and Sets working. I ran my code against you test: 34 passed, 21 failed. Of the 21, symbols and discard (skip) are expected because I need to fully implement those. However, there are some special cases I need to look at too such as `<` | `>`, big decimals & ints, and exponentials. I'll keep at it but thanks for the tests. 

BTW, have you seen [https://github.com/shaunxcode/edn-tests/tree/master/valid-edn](https://github.com/shaunxcode/edn-tests/tree/master/valid-edn)?

**Comment by russolsen** [comment]
Ed,

Glad you are finding the new tests useful. As for https://github.com/shaunxcode/edn-tests/tree/master/valid-edn -- well further evidence that I am an idiot. I'll have a look at pulling these tests into end-ruby. Thanks for pointing it out.

R

**Comment by edporras** [comment]
Hi Russ, 

I'm down to 10 failed tests and 8 of those are discards. The other two seem to be a value representation with Big Ints and Big Decimals. I need to create the correct types from the C side. 

I've implemented use tagged elements by replicating your tag registration and then making a call to create an EDN::Type::Symbol so the output matches. I'll obviously clean that up if everything looks good for the integration.

I'll push the latest code once I fix the Big value output.

**Comment by edporras** [comment]
Russ,

I have discards working so all your tests with the exception of Big Int and Big Decimal are passing. I've pushed the code and released v0.2.0 of the gem.

Aside from the Big value issue, I also need to support `-` and `+` standalone as well as symbols with a leading `-`. Currently, `edn_turbo` is set up to only expect numbers with a leading `-` hence why these tests are failing. I'll just have to refactor things and, perhaps, create an operator-parsing machine that then makes calls to the symbol and number parsers accordingly. I'll be working on that this week.

**Comment by edporras** [comment]
Hi Russ, I didn't get much sleep last night cause I couldn't stop thinking about getting this done. :)

So, v0.2.1 is out with support for BigNum, operators, and operator-led symbols. I'm passing all tests in your suite and all the ones in [shaunxcode's valid-edn](https://github.com/shaunxcode/edn-tests/tree/master/valid-edn). I used output from `edn-ruby` to create the reference files for these so I do have a question about [set-with-list](https://github.com/shaunxcode/edn-tests/blob/master/valid-edn/set-with-list.edn) which looks like this:

```#{(foo bar)}```

Obviously, when converted to ruby, EDN lists are treated as arrays so `(foo bar)` is interpreted as `[foo bar]`. However, I noticed that parsing the file with `edn_ruby` produces this output: 

```#<Set: {[#<EDN::Type::Symbol:0x007fde52a66570 @symbol=:foo>,
  #<EDN::Type::Symbol:0x007fde52a65ee0 @symbol=:bar>]}>```

This looks like a set with a single element (the 2-item array). Looking at the [ruby Set documentation](http://ruby-doc.org/stdlib-2.2.2/libdoc/set/rdoc/Set.html#method-c-new) it seems that passing an array argument to `Set`, adds the elements individually so the output I was originally expecting was just a set with 2 items:

```#<Set: {#<EDN::Type::Symbol:0x007fde52a66570 @symbol=:foo>,
  #<EDN::Type::Symbol:0x007fde52a65ee0 @symbol=:bar>}>```

I'm not sure what is correct since I don't know the expected behavior of adding an EDN list converted to a ruby array into a Set. Regardless, the reference file I had to create to generate your output looks like so:

```Set.new([[EDN::Type::Symbol.new("foo"), EDN::Type::Symbol.new("bar")]])```

For now I'm leaving things so it matches your output. Hopefully we can get some feedback to confirm this; otherwise the fix is to populate the set with the individual items from the array.

Let me know what you think. Thank you.

**Comment by edporras** [comment]
BTW, I ran the benchmark tests from [issue 12](https://github.com/relevance/edn-ruby/issues/12):

```irb(main):026:0* s = "[{\"x\" {\"id\" \"/model/952\", \"model_name\" \"person\", \"ancestors\" [\"record\" \"asset\"], \"format\" \"edn\"}, \"id\" 952, \"name\" nil, \"model_name\" \"person\", \"rel\" {}, \"description\" nil, \"age\" nil, \"updated_at\" nil, \"created_at\" nil, \"anniversary\" nil, \"job\" nil, \"start_date\" nil, \"username\" nil, \"vacation_start\" nil, \"vacation_end\" nil, \"expenses\" nil, \"rate\" nil, \"display_name\" nil, \"gross_profit_per_month\" nil}]"
=> "[{\"x\" {\"id\" \"/model/952\", \"model_name\" \"person\", \"ancestors\" [\"record\" \"asset\"], \"format\" \"edn\"}, \"id\" 952, \"name\" nil, \"model_name\" \"person\", \"rel\" {}, \"description\" nil, \"age\" nil, \"updated_at\" nil, \"created_at\" nil, \"anniversary\" nil, \"job\" nil, \"start_date\" nil, \"username\" nil, \"vacation_start\" nil, \"vacation_end\" nil, \"expenses\" nil, \"rate\" nil, \"display_name\" nil, \"gross_profit_per_month\" nil}]"
irb(main):027:0> j = EDN::Reader.new(s).read.to_json
=> "[{\"x\":{\"id\":\"/model/952\",\"model_name\":\"person\",\"ancestors\":[\"record\",\"asset\"],\"format\":\"edn\"},\"id\":952,\"name\":null,\"model_name\":\"person\",\"rel\":{},\"description\":null,\"age\":null,\"updated_at\":null,\"created_at\":null,\"anniversary\":null,\"job\":null,\"start_date\":null,\"username\":null,\"vacation_start\":null,\"vacation_end\":null,\"expenses\":null,\"rate\":null,\"display_name\":null,\"gross_profit_per_month\":null}]"
irb(main):028:0> Benchmark.realtime { 100.times { JSON.parse(j) }}
=> 0.002709
irb(main):029:0> Benchmark.realtime { 100000.times { JSON.parse(j) }}
=> 2.180127
irb(main):030:0> Benchmark.realtime { 100.times { EDN::read(s) } }
=> 0.087262
irb(main):031:0> Benchmark.realtime { 100000.times { EDN::read(s) } }
=> 78.971977
irb(main):032:0> Benchmark.realtime { 100.times { EDNT::read(s) } }
=> 0.006783
irb(main):033:0> Benchmark.realtime { 100000.times { EDNT::read(s) } }
=> 4.425388```

**Comment by edporras** [comment]
Hi Russ,

I've pushed [v0.3.0](https://rubygems.org/gems/edn_turbo/versions/0.3.0). `edn_turbo` no longer requires `rice` and I've added a call to support your reader's token-by-token parsing. Removing `rice` also has performance gains. I wrote a script to run the above tests and here's the output:

```ruby
edn v1.0.7 | edn_turbo v0.3.0
EDN::read 100x
0.079289
EDNT::read 100x
0.005534
EDN::read 100000x
73.699227
EDNT::read 100000x
2.453168
```

I'm working to hook it into `edn-ruby` now but I'll likely request some feedback regarding installation, etc. Hopefully sometime next week.

**Comment by russolsen** [comment]
Hey Ed,

Sorry I haven't gotten back to you lately. I am glad to see you are making progress and looking forward to pulling in your code: 30X performance gain would be great.

R

**Comment by edporras** [comment]
hi Russ,

While integration my parser, I discovered EDN metadata is a thing so I had to add support for it :). I've pushed [v0.3.1](https://rubygems.org/gems/edn_turbo/versions/0.3.1) and I'm now resuming the merge. I'd like your feedback on a few things I've encountered though:

* Tag handling seems to have duplicated code?:

`EDN` instantiates `@tags` in [lib/edn.rb](https://github.com/relevance/edn-ruby/blob/master/lib/edn.rb) and `TAGS` in [lib/edb/parser.rb](https://github.com/relevance/edn-ruby/blob/master/lib/edn/parser.rb). Both define methods that seem to do the exact same thing. Maybe there's something I'm not following but, regardless, my parser needs access to this so I would propose to remove the duplication from parser.rb and move them to a file such as parser_common.rb that both parsers can share. I've tried accessing things in lib/edn.rb from the C-side but I haven't been able to figure it out. However, I'm able to access things in files within lib/edn.

* Related to tags for the built-ins `#inst` and `#uuid`, how do you feel about changing registration to this:

```ruby
  @tags = {
    # built-in tagged elements
    "inst" => lambda { |*a| DateTime.parse(*a) },
    "uuid" => lambda { |*a| String.new(*a) }
  }
```

and then adding a check so they can't be overridden by the user:

```ruby
  def self.register(tag, func = nil, &block)
    # don't allow re-registration of built-in tags
    return if tag == "inst" && tag == "uuid"
...
```

This is not necessary for my parser though.

* Similar to tagged element handling, I need access to the snippet in `read_meta` that extends the value and assigns the interpreted metadata:

```ruby
      metadata = raw_metadata.reverse.reduce({}) do |acc, m|
        case m
        when Symbol then acc.merge(m => true)
        when EDN::Type::Symbol then acc.merge(:tag => m)
        else acc.merge(m)
        end
      end
      metadata.empty? ? nil : metadata
```

so I'm thinking of moving this into a method outside of your parser.

* I also need access to `EOF`.

* And now, the hard part: we can handle selecting which parser to use with something like an argument passed to the Reader. Or maybe it should be an option at install time. This is where I'm not sure how to proceed as my parser does require a c++ compiler and icu4c. I'm reading up on passing arguments to `bundle install` and `rake` to see what can be done.

Regardless, I think we should first release an update with a major version change that has your parser as the default one. The major version would hopefully indicate there's something new so they can try installing it with the new parser if they want. I would definitely like to hear feedback from users to see what they run into when trying to install and, obviously, when they run things with the new parser. But I don't want to cause a big disruption if people choose to upgrade blindly (hence, the major version bump - perhaps 2.0.0?)

What do you think? I'll push changes today so you can start looking at the branch. I've ran into some issues getting things running so I hope to be done by EOD.

Thanks.

**Comment by russolsen** [comment]
Hey Ed,

A quick look seems to indicate that there is indeed some duplication between parser and end. I'll clean that up first chance I get. 

I'm really kind of against having a special case for inst and uuid, but ultimately we should probably check if the EDN spec has anything to say about it and also what the Clojure implementation does. 

I can certainly `move the metadata function somewhere else. 

So I agree that the defs of EOF (and NOTHING) should move to edn.rb, but this should be transparent to you: No matter where the def is, EDN::EOF (or the C equivalent) should get you there.

I *think* that what people do in a situation like this is to have two different gems or perhaps versions of gems, one that is pure Ruby and one that is native. I would think that if we try to mix them then the folks who don't have a C compiler or whatever are going to have issues installing.

I've been crazy busy lately, but I will have a look this week.

R

**Comment by edporras** [comment]
hi Russ,

I ran into another issue on Friday, this time dealing with symbols. I didn't understand the way the spec worked until I started to integrate it (I had just been testing against the exemplars) but I'm hoping this is the last of it. :(

And, yes, the merge is tricky. I was leaning to a way to specify which argument but I haven't found a clean way to do it. `json-ragel` uses environment variables, which I'm not really excited about.

Thanks for the reply and no worries. We'll get there. :)

**Comment by russolsen** [comment]
Ed,

For quicker turnaround, feel free to email me directly at russ@russolsen.com

R

**Comment by russolsen** [comment]
Oh, and environment variables are the work of the Devil. And they are not even his best stuff.

**Comment by russolsen** [comment]
I'm very happy to say that with the release of version 1.1, this issue is *closed*!
